export const images = [
    {title: "Item 1", subtitle: "Cover picture", img: `${process.env.PUBLIC_URL}/CarouselImages/UAC.png` },
    {title: "Item 2", subtitle: "Picture 1", img: `${process.env.PUBLIC_URL}/CarouselImages/UAC1.jpg` },
    {title: "Item 3", subtitle: "Picture 2", img: `${process.env.PUBLIC_URL}/CarouselImages/UAC2.jpg` },
    {title: "Item 4", subtitle: "Picture 3", img: `${process.env.PUBLIC_URL}/CarouselImages/UAC3.png` },
    {title: "Item 5", subtitle: "Cover picture", img: `${process.env.PUBLIC_URL}/CarouselImages/CI2021.png` },
    {title: "Item 6", subtitle: "Picture 1", img: `${process.env.PUBLIC_URL}/CarouselImages/CI.png` },
    {title: "Item 7", subtitle: "Cover picture", img: `${process.env.PUBLIC_URL}/CarouselImages/SFA.png` },
    {title: "Item 8", subtitle: "Picture 1", img: `${process.env.PUBLIC_URL}/CarouselImages/SFA1.png` },
    {title: "Item 9", subtitle: "Picture 2", img: `${process.env.PUBLIC_URL}/CarouselImages/SFA2.jpg` },
    {title: "Item 10", subtitle: "Cover picture", img: `${process.env.PUBLIC_URL}/CarouselImages/Delicasea.png` },
    {title: "Item 11", subtitle: "Picture 1", img: `${process.env.PUBLIC_URL}/CarouselImages/D1.jpg` },
    {title: "Item 12", subtitle: "Picture 2", img: `${process.env.PUBLIC_URL}/CarouselImages/D2.jpg` },
    {title: "Item 13", subtitle: "Picture 3", img: `${process.env.PUBLIC_URL}/CarouselImages/D3.jpg` },
    {title: "Item 14", subtitle: "Cover picture", img: `${process.env.PUBLIC_URL}/CarouselImages/YECC2021.png` },
    {title: "Item 15", subtitle: "Picture 1", img: `${process.env.PUBLIC_URL}/CarouselImages/YECC.png` },
];